importScripts("precache-manifest.df24a9fff981240ecec66bd175ed9d5e.js", "https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js");

// manifest import and workbox imports will be autogenerated by webpack
workbox.precaching.precacheAndRoute(self.__precacheManifest || []);
